### ISSUE TITLE
Elasticsearch 5.0 Outside can not connect elasticsearch in Docker

### ISSUE THREAD

**Issue by sunfmin** [sunfmin/notebook#11]
https://github.com/olivere/elastic/wiki/Docker

Add `-Enetwork.publish_host=127.0.0.1` to docker-compose.yml

```yml
    elasticsearch:
        image: elasticsearch:5.0
        environment:
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        entrypoint:
        - "/docker-entrypoint.sh"
        - "-Enetwork.publish_host=127.0.0.1"
        ports:
        - "9200:9200"
        - "9300:9200"

```
