### ISSUE TITLE
Create postgres docker container that output all sql in logs for development

### ISSUE THREAD

**Issue by sunfmin** [sunfmin/notebook#48]
docker-compose.yml

```yml
version: '3'
services:
    postgres:
        image: postgres:11
        environment:
        - "POSTGRES_USER=homeland"
        - "POSTGRES_PASSWORD=123"
        - "POSTGRES_DB=homeland_test"
        ports:
        - "5002:5432"
        command:
        - "postgres"
        - "-c"
        - "log_statement=all"

```
